In [6]:
import numpy as np
import skfuzzy as fuzz 
import matplotlib.pyplot as plt

In [7]:
np.random.seed(0)
center=0.5 
spread=0.1 
data=center+spread*np.random.randn(2,100)
data=np.clip(data,0,1)

In [9]:
n_clusters=3 
m=1.7 
error=1e-5
maxiter=2000 

In [10]:
cntr,u,_,_,_,_,fpc=fuzz.cluster.cmeans(data,c=n_clusters,m=m,error=error,maxiter=maxiter,init=None)

hard_clusters=np.argmax(u,axis=0)

In [12]:
print("cluster centers:\n",cntr)
print("\nFuzzy memebership matrix:")
print(u[:,:5])

cluster centers:
 [[0.40427944 0.44688713]
 [0.57608357 0.43108734]
 [0.53151692 0.61555506]]

Fuzzy memebership matrix:
[[0.0753945  0.103008   0.03041289 0.09668828 0.07004986]
 [0.16579475 0.86917327 0.95209853 0.36321813 0.85265308]
 [0.75881075 0.02781873 0.01748858 0.54009359 0.07729706]]


In [13]:
fig ,ax=plt.subplots

TypeError: cannot unpack non-iterable function object