In [3]:
!pip install scikit-learn scikit-fuzzy
import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 920.8/920.8 kB 2.4 MB/s  0:00:00 eta 0:00:01


In [4]:
np.random.seed(0)
center=0.5
spread=0.1 
data=center+spread*np.random.randn(2,100)
data=np.clip(data,0,1)

fuzzy c means parameter 


In [ ]:
n_clusters=3
m=1.7
error=1e-5 
maxiter=1020

In [10]:
cntr,u,_,_,_,_,fpc=fuzz.cluster.cmeans(data,c=n_clusters,m=m,maxiter=maxiter,error=error,init=None)
hard_clusters=np.argmax(u,axis=0)

In [12]:
print("Amar bou duteee:\n",cntr)
print("n Fuzzy membership matrix:")
print(u[:,:5])

Amar bou duteee:
 [[0.40427945 0.44688713]
 [0.53151691 0.61555507]
 [0.57608358 0.43108735]]
n Fuzzy membership matrix:
[[0.07539451 0.10300807 0.0304129  0.09668829 0.07004985]
 [0.75881069 0.02781874 0.01748859 0.5400935  0.07729704]
 [0.1657948  0.86917319 0.95209851 0.36321821 0.8526531 ]]


visualization 

In [1]:
fig,ax=plt.subplots(figsize=(8,6))
for i in range(n_clusters):
    ax.scatter(data[0],data[1],c=u[i],cmap='coolwarm',alpha=0.5,label=f'Fuzzy cluster{i+1}')

markers=['o','s','^']
colors=['blue','red','orange']
for i in range(n_clusters):
    cluster_points=data[:,hard_clusters==i]
    ax.scatter(cluster_points[0],cluster_points[1],c=colors[i],marker=markers[i],edgecolor='k',s=80,label='Cluster Centers')
   
ax.scatter(cntr[:,0],cntr[:,1],c='red',marker='X',s=200,label='Cluster Centers')

ax.set_title('Fuzzy C-means')
ax.set_xlabel('Feature 1')
ax.set_ylabel('Feature 2')
ax.legend(loc='upper left')
plt.grid(True)
plt.show()

NameError: name 'plt' is not defined